import Head from "next/head"
import Header from "./components/Header"
import { useMoralis } from "react-moralis"
import Contribute from "./components/Contribute"

const supportedChains = ["31337", "4"]

export default function Home() {
    const { isWeb3Enabled, chainId } = useMoralis()
    return (
        <div className="bg-gradient-to-r from-cyan-500 to-blue-500 min-h-screen">
            <Head>
                <title>Web3 Funding App </title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header />
            {isWeb3Enabled ? (
                <div>
                    {supportedChains.includes(parseInt(chainId).toString()) ? (
                        <div className="flex justify-center mt-20">
                            <Contribute />
                        </div>
                    ) : (
                        <div className="text-white p-5 ">
                            {`Please switch to a supported chainId. The supported chain Ids are: ${supportedChains} !!`}
                        </div>
                    )}
                </div>
            ) : null}
        </div>
    )
}
